services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: intdorsys.web.api
    env_file:
      - ../.env
    ports:
      - "${BACKEND_PORT:-5050}:${BACKEND_PORT:-5050}"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:${BACKEND_PORT:-5050}
      Jwt__Secret: ${JWT_SECRET}
      ConnectionStrings__Battle: "Host=host.docker.internal;Port=${DB_PORT_HOST:-5433};Database=${DB_NAME:-dorm};Username=${DB_USER:-postgres};Password=${DB_PASSWORD:-admin}"